# Generated by Django 6.0.1 on 2026-01-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conceptos_basicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={
                "ordering": ["-fecha_inicio"],
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Slug URL"
            ),
        ),
    ]
