# Generated by Django 6.0.1 on 2026-01-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conceptos_basicos", "0002_alter_curso_options_curso_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("BASICO", "Básico"),
                    ("INTERMEDIO", "Intermedio"),
                    ("AVANZADO", "Avanzado"),
                ],
                default="BASICO",
                max_length=10,
                verbose_name="Nivel",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Precio"
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="publicado",
            field=models.BooleanField(default=False, verbose_name="¿Publicado?"),
        ),
        migrations.AddField(
            model_name="curso",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="conceptos_basicos.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía")),
                ("website", models.URLField(blank=True, verbose_name="Sitio Web")),
                (
                    "estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to="conceptos_basicos.estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Estudiante",
                "verbose_name_plural": "Perfiles de Estudiante",
            },
        ),
    ]
