# Generated by Django 6.0.1 on 2026-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conceptos_basicos", "0003_categoria_curso_nivel_curso_precio_curso_publicado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="fecha_inicio",
            field=models.DateField(db_index=True, verbose_name="Fecha de Inicio"),
        ),
    ]
