# Generated by Django 6.0.1 on 2026-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("TEACHER", "Profesor"),
                    ("STUDENT", "Estudiante"),
                ],
                default="STUDENT",
                max_length=50,
                verbose_name="Rol",
            ),
        ),
    ]
