# Generated by Django 6.0.1

from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal

def create_groups(apps, schema_editor):
    # Ensure permissions are created for all apps to avoid Race Conditions
    # This invokes the logic that populates the Permission table based on models
    emit_post_migrate_signal(2, False, 'default')

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create Groups
    teacher_group, _ = Group.objects.get_or_create(name='TEACHER')
    student_group, _ = Group.objects.get_or_create(name='STUDENT')

    # Assign Permissions
    # We look for 'add_curso' in 'conceptos_basicos'
    try:
        add_curso = Permission.objects.get(
            codename='add_curso',
            content_type__app_label='conceptos_basicos'
        )
        teacher_group.permissions.add(add_curso)
    except Permission.DoesNotExist:
        # Should not happen if emit_post_migrate_signal works, but safety first
        print("Warning: Permission 'add_curso' not found. Skipping assignment.")

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['TEACHER', 'STUDENT']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_role"),
        ("conceptos_basicos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
